version: 0.1

phases:
  pre_build:
    commands:
      - apk update
      - apk add py-pip zip
      - pip install awscli
  build:
    commands:
      - >-
          sbt clean assembly;
          exit_code=$?;
          if [ $exit_code != 0 ]; then
          aws sns publish --phone-number "${BUILD_FAILURE_PHONE_NUM}" --message "Dossier Lambda Project failed to build on $(TZ='America/Los_Angeles' date)";
          fi;
          exit $exit_code
  post_build:
    commands:
      - aws s3api put-object --storage-class STANDARD_IA --bucket ${LAMBDA_CODE_JAR_BUCKET} --key ${LAMBDA_CODE_JAR_KEY} --body target/S3DropboxLambda-assembly-*.jar
