version: 0.1

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get -y install python3-pip
      - pip3 install awscli
  build:
    commands:
      - >-
          sbt clean assembly;
          exit_code=$?;
          if [ $exit_code != 0 ]; then
          aws sns publish --phone-number "${BUILD_FAILURE_PHONE_NUM}" --message "Dossier Lambda Project failed to build on $(TZ='America/Los_Angeles' date)";
          fi;
          exit $exit_code
  post_build:
    commands:
      - aws s3api put-object
          --storage-class STANDARD_IA
          --bucket ${LAMBDA_CODE_JAR_BUCKET}
          --key ${LAMBDA_CODE_JAR_KEY}
          --body target/S3DropboxLambda-assembly-1.0.jar
      - aws lambda update-function-configuration
          --function-name ${LAMBDA_FUNCTION_ARN}
          --runtime java8
          --handler 'com.s3dropbox.lambda.LambdaMain::handleRequest'
          --environment "Variables={DBX_CREDENTIAL_S3_BUCKET=${DBX_CREDENTIAL_S3_BUCKET},DBX_CREDENTIAL_S3_KEY=${DBX_CREDENTIAL_S3_KEY},DBX_CREDENTIAL_KMS_ID=${DBX_CREDENTIAL_KMS_ID}}"
      - aws lambda update-function-code
          --function-name ${LAMBDA_FUNCTION_ARN}
          --s3-bucket ${LAMBDA_CODE_JAR_BUCKET}
          --s3-key ${LAMBDA_CODE_JAR_KEY}
